-- Database: sop_finance

-- DROP DATABASE IF EXISTS sop_finance;

CREATE DATABASE sop_finance
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Table: public.despesa

-- DROP TABLE IF EXISTS public.despesa;

CREATE TABLE IF NOT EXISTS public.despesa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    credor character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data_protocolo timestamp(6) without time zone NOT NULL,
    data_vencimento date NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_protocolo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    tipo_despesa character varying(255) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(38,2) NOT NULL,
    CONSTRAINT despesa_pkey PRIMARY KEY (id),
    CONSTRAINT ukn7uxif67o0se2s46qtwhodxcb UNIQUE (numero_protocolo)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.despesa
    OWNER to postgres;

-- Table: public.empenho

-- DROP TABLE IF EXISTS public.empenho;

CREATE TABLE IF NOT EXISTS public.empenho
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_empenho date NOT NULL,
    numero_empenho character varying(255) COLLATE pg_catalog."default" NOT NULL,
    valor_empenhado numeric(38,2) NOT NULL,
    despesa_id bigint NOT NULL,
    CONSTRAINT empenho_pkey PRIMARY KEY (id),
    CONSTRAINT ukb76ftfjibtvps7c9llcp3h8wy UNIQUE (numero_empenho),
    CONSTRAINT fkk8dt2k7g3pdscp252s2t7s5u3 FOREIGN KEY (despesa_id)
        REFERENCES public.despesa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empenho
    OWNER to postgres;

-- Table: public.pagamento

-- DROP TABLE IF EXISTS public.pagamento;

CREATE TABLE IF NOT EXISTS public.pagamento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_pagamento date NOT NULL,
    forma_pagamento character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_pagamento character varying(255) COLLATE pg_catalog."default" NOT NULL,
    valor_pago numeric(38,2) NOT NULL,
    empenho_id bigint NOT NULL,
    CONSTRAINT pagamento_pkey PRIMARY KEY (id),
    CONSTRAINT uknj79sm8mt7rk9eushrj4ys1sd UNIQUE (numero_pagamento),
    CONSTRAINT fk5rg11s21wg52bd9ubog6kn5bi FOREIGN KEY (empenho_id)
        REFERENCES public.empenho (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pagamento
    OWNER to postgres;

-- Table: public.usuario

-- DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL DEFAULT nextval('usuario_id_seq'::regclass),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk_pimirdqbf828ejsgnxmc3kfix UNIQUE (user_name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to postgres;